// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SCI LAB 360",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen relative`}
      >
        {/* Background image layer */}
        <div
          className="fixed top-0 left-0 w-full h-full bg-cover bg-center bg-no-repeat opacity-20 -z-10"
          style={{ backgroundImage: "url('/assets/images/background.jpg')" }}
        ></div>

        {/* Sidebar */}
        <NavBar />

        {/* Main content with sidebar offset */}
        <div className="relative z-10 pt-6 ml-0 md:ml-44 ">
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
